#!/usr/bin/env bash

PATH="$(python -m site --user-base)/bin:$PATH"
curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user --force-reinstall
rm -f get-pip.py
pip install --user --upgrade --force-reinstall pip virtualenv
