#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  pushd "$phome" > /dev/null
  mkdir -p "$phome/vendor/virtualenv"
  virtualenv "$phome/vendor/virtualenv"
  set +u; source "$phome/vendor/virtualenv/bin/activate"; set -u
  if [[ "$#" == 0 ]]; then
    if [[ -f requirements.txt ]]; then
      pip install -r requirements.txt
    fi
  else
    eval "$@"
  fi
  popd > /dev/null
}

source sub "$0" "$@"
