#!/usr/bin/env bash

function main {
  local phome="$1"; shift

  if [[ -f "$phome/requirements.txt" ]]; then
    return 0
  fi

  echo "WARNING: requirements.txt not found" 1>&2
  return 1
}

source sub "$0" "$@"
