#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  pipenv27 install --two --python "$(which python2.7)" "$@"
}

source sub "$0" "$@"
