#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  env PIP_WHEEL=1 block compile virtualenv "$@"
}

source sub "$0" "$@"
