#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  env PYTHON=python2.7 PIP=pip2.7 VENV=virtualenv-2.7 block compile virtualenv "$@"
}

source sub "$0" "$@"
