#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  PATH="$PKG_HOME/install/bin:$PATH"

  : ${PYTHON:=python3.5}
  : ${PIP:=pip3.5}
  : ${VENV:=pyvenv-3.5}
  pushd "$phome" > /dev/null
  mkdir -p "$phome/vendor/virtualenv"
  ${VENV} "$phome/vendor/virtualenv"
  set +u; source "$phome/vendor/virtualenv/bin/activate"; set -u
  "${PIP}" install --no-cache-dir --upgrade pip
  if [[ "$#" == 0 ]]; then
    if [[ -f requirements.txt ]]; then
      "$PIP" install --no-cache-dir -r requirements.txt
    fi
  else
    eval "$@"
  fi
  popd > /dev/null
}

source sub "$0" "$@"
