#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  export PATH="$shome/vendor/virtualenv/bin:$PATH"

  if [[ "$#" == 0 ]]; then
    set -- install --three
  fi

  cd "$phome"
  local nm_block="${phome##*/}"

  if [[ ! -L Pipfile.lock ]]; then
    rsync -ia Pipfile.lock "${BOARD_PATH}/Pipfile.lock.${nm_block}"
  fi
  ln -nfs "${BOARD_PATH}/Pipfile.lock.${nm_block}" "Pipfile.lock"

  pipenv "$@"

  if [[ ! -L Pipfile.lock ]]; then
    rsync -ia Pipfile.lock "${BOARD_PATH}/Pipfile.lock.${nm_block}"
  fi
  ln -nfs "${BOARD_PATH}/Pipfile.lock.${nm_block}" "Pipfile.lock"
}

source sub "$0" "$@"
