#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$PKG_HOME/install/bin:$PATH"

  : ${PIP_WHEEL:=}
  : ${PYTHON:=python3.6}
  : ${PIP:=pip3.6}
  : ${VENV:=virtualenv-3.6}
  pushd "$phome" > /dev/null
  mkdir -p "$phome/vendor/virtualenv"
  ${VENV} "$phome/vendor/virtualenv"
  set +u; source "$phome/vendor/virtualenv/bin/activate"; set -u
  "${PIP}" install --no-cache-dir pip wheel
  if [[ "$#" == 0 ]]; then
    local pth_requirements='requirements.txt'
    if [[ ! -f "$pth_requirements" ]]; then
      pth_requirements="${BOARD_PATH}/requirements-$(cat "$phome/.repo-name" | cut -d/ -f2).txt"
    fi

    if [[ -f "$pth_requirements" ]]; then
      local pth_wheel="$(echo "$phome" | perl -pe 's{[^\w]+}{-}g')"
      pth_wheel="${pth_wheel#-}"
      pth_wheel="${pth_wheel%-}"
      pth_wheel="${CACHE_DIR}/wheels/${ID_INSTALL}/${pth_wheel}"

      mkdir -vp "$pth_wheel"

      if [[ -n "${PIP_WHEEL}" ]]; then
        "$PIP" wheel --no-cache-dir --wheel-dir="$pth_wheel" -r "$pth_requirements"
      fi

      "$PIP" install --no-cache-dir --use-wheel --find-links="$pth_wheel" -r "$pth_requirements"
    fi
  else
    eval "$@"
  fi
  popd > /dev/null
}

source sub "$0" "$@"
