#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  shift; shift; shift
  env PIP_WHEEL=1 block compile virtualenv27 "$@"
}

source sub "$0" "$@"
