#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  export PATH="$shome/vendor/virtualenv/bin:$PATH"

  if [[ "$#" == 0 ]]; then
    case "$(python --version 2>&1 | awk '{print $2}')" in
      2.*)
        set -- install --two
        ;;
      3.*)
        set -- install --three
        ;;
      esac
  fi

  cd "$phome"
  local nm_block="${phome##*/}"

  if [[ ! -L Pipfile.lock ]]; then
    if [[ -f Pipfle.lock ]]; then
      cat Pipfile.lock | jq -r '.default[] |= del(.hashes)' > "${BOARD_PATH}/Pipfile.lock.${nm_block}"
    fi
  fi
  ln -nfs "${BOARD_PATH}/Pipfile.lock.${nm_block}" "Pipfile.lock"

  pipenv "$@"

  if [[ ! -L Pipfile.lock ]]; then
    if [[ -f Pipfle.lock ]]; then
      cat Pipfile.lock | jq -r '.default[] |= del(.hashes)' > "${BOARD_PATH}/Pipfile.lock.${nm_block}"
    fi
  fi
  ln -nfs "${BOARD_PATH}/Pipfile.lock.${nm_block}" "Pipfile.lock"
}

source sub "$0" "$@"
