#!/usr/bin/env bash

function main {
  local phome="$1"; shift
  local pth_cache="$1"; shift
  local pth_env="$1"; shift

  : ${PYTHON:=python3.5}
  : ${PIP:=pip} # there is a pip along with pip2.7

  pushd "$phome" > /dev/null
  mkdir -p "$phome/vendor/virtualenv"
  virtualenv -p "${PYTHON}" "$phome/vendor/virtualenv"
  set +u; source "$phome/vendor/virtualenv/bin/activate"; set -u
  if [[ "$#" == 0 ]]; then
    if [[ -f requirements.txt ]]; then
      "$PIP" install -r requirements.txt
    fi
  else
    eval "$@"
  fi
  popd > /dev/null
}

source sub "$0" "$@"
