#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export PYTHON_VERSION_DEFAULT="${0##*py}"
  export PIP_VERSION_DEFAULT="$(echo "${PYTHON_VERSION_DEFAULT}" | perl -pe 's{(.)}{$1.}')"

  case "$PYTHON_VERSION_DEFAULT" in
    36)
      export PYTHON="python3.6"
      export PIP="pip3.6"
      export VENV="pyvenv-3.6"
      ;;
  esac

  exec "$@"
}

source sub "$0" "$@"
