#!/usr/bin/env bash

set -efu

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      sudo aptitude update
      sudo aptitude install -y python-setuptools python-dev
      sudo aptitude install -y libffi-dev libssl-dev # TODO belongs in a build block
      ;;
  esac

  python "$shome/script/install-pip" --root "$shome/install"
  pip install virtualenv --root "$shome/install" --upgrade
}

main "$@"
