#!/usr/bin/env bash

set -efu

function main {
  case "$(uname -s)" in
    Linux)
      sudo aptitude update
      sudo aptitude install -y python-setuptools python-dev
      ;;
  esac

  sudo -H easy_install pip
  sudo -H pip install virtualenv --upgrade
}

main "$@"
