#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if ! type -P virtualenv-2.7 >/dev/null; then
    return 1
  fi

  if ! type -P virtualenv-3.6 >/dev/null; then
    return 1
  fi

  case "$(uname -s)" in
    Darwin)
      if [[ ! -x "$(python -m site --user-base)/bin/virtualenv" ]]; then
        return 1
      fi
      ;;
  esac

  return 0
}

source sub "$0" "$@"
