#!/usr/bin/env bash

function profile {
  local shome="${_python_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/exec:$PATH"

  export PYTHON_VERSION_DEFAULT=35
}

profile
