#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$PKG_HOME/install/bin/pyvenv-3.6" ]]; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"
