#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$shome/install/usr/local/bin/virtualenv" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"
