#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_python27="$(python2.7 --version 2>&1 | awk 'NR == 1 {print $2}')"
  local ver_python36="$(python3.6 --version 2>&1 | awk 'NR == 1 {print $2}')"

  jq -n \
    --arg python27 "$ver_python27" \
    --arg python36 "$ver_python36" \
    '{python27: $python27, python36: $python36}'
}

version "$@"
